[application]

# App (Project) Name
name = "notepad-minus-minus"
icon = ["assets/favicon.ico"]

[web.app]

# HTML title tag content
title = "notepad-minus-minus"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
